### ISSUE TITLE
How the features extracted from current frame merges with similarity maps out of Merge module in decoder?

### ISSUE THREAD

**Issue by ArchNew** [Storife/RANet#2]
According to the Figure 2 in the paper, the decoder takes two things in, one is merged similarity maps and mask from 'Merge' module, the other is the features of the current frame extracted directly by Siamese Encoder.

But I can't find anywhere how the decoder uses those two things. Are they concatenated together before going into the Decoder, or there is some sort of operation? Such as convolution, element-wise multiplication or just simple addition?

**Comment by Storife** [comment]
Hi, I think you can find the answer in our Supplementary File, which can be downloaded in our GitHub main page.

**Comment by ArchNew** [comment]
> Hi, I think you can find the answer in our Supplementary File, which can be downloaded in our GitHub main page.

Thanks! I think I find what I want.
